### ISSUE TITLE
Rope autocompletion is broken

### ISSUE THREAD

**Issue by jgosmann** [klen/python-mode#366]
When using the [YouCompleteMe plugin](https://github.com/Valloric/YouCompleteMe) together with python-mode auto-completion is broken. For example after typing ```self.``` a list of choices is shown, but this will not get narrowed down after typing further characters. Though it does get narrowed down when deleting a character. Also the detection where the completion should end is not working. This sometimes replaces wrong parts, e.g. doing a completion after typing ```self.some_function(some_var``` might result in ```self.some_variable``` instead of ```self.some_function(some_variable```.

If you set ```g:pymode_rope_complete_on_dot = 0```, auto-completion seems to work, but won't give you any auto-completion choices for python modules.

The commit introducing this problem is [886d08bca2fc13eb27fde8a8ded469e979d9a454](https://github.com/klen/python-mode/commit/886d08bca2fc13eb27fde8a8ded469e979d9a454). But my understanding so far is not sufficient to fix this myself.

**Comment by dset0x** [comment]
@jgosmann I cannot reproduce this issue on current `development` branch. Could you try again?

**Comment by jgosmann** [comment]
Seems to work on the current `development` branch.
