### ISSUE TITLE
Pymode omnicompletion broken under vim 7.3 on MacOSX

### ISSUE THREAD

**Issue by manphiz** [klen/python-mode#426]
Using vim 7.3 shipped with MacOSX, when trying to complete using omnicomplete (^x^o) it errors with the following messages:
```
[Pymode] Regenerate autoimport cache.
[Pymode]: error: flush
```
There is no problem when using MacVIM. I'm on 10.9 mavericks.

Relevant configurations in .vimrc:
```
" Python-mode settings.
let g:pymode_options = 0
let g:pymode_indent = 1
let g:pymode_folding = 0
let g:pymode_rope_lookup_project = 0
let g:pymode_rope_complete_on_dot = 0
```
Let me know if you need more information.

**Comment by klen** [comment]
Should be fixed now.
