### ISSUE TITLE
PyMode Error when on trying to write onto a file not in worktree

### ISSUE THREAD

**Issue by nishantvarma** [klen/python-mode#440]
Hi There ,

I was just working on a Gdiff {revision} and seeing the changes . 
By mistake I modified on the {revision} file instead of the working tree file !

It was good that I found an error like this (made me think pymode or me causing the mistake) : 

Error detected while processing function pymode#buffer_post_write:                                                                                                        
line    2:                                                                                                                                                                
E121: Undefined variable: b:pymode_modified                                                                                                                               
E15: Invalid expression: b:pymode_modified && g:pymode_rope_regenerate_on_write                                                                                           
Press ENTER or type command to continue               

Helped me realize that I am on the wrong file ! 

Can you please check if you can make the error user friendly though by posting some suggestions or anything like that ? Just a thought .  As I am pretty sure many might do the same . Its just a suggestion .

**Comment by klen** [comment]
Fixed
