### ISSUE TITLE
Is it possible to prevent the location list from being displayed after a check.

### ISSUE THREAD

**Issue by symbolix** [klen/python-mode#476]
Hi,

I would like to be able to toggle "on" and "off" the location list myself. So is it possible to have the option of "not" displaying the location list after :PymodeLint is executed. It still should populate the location list, but not display it. So that I can display it myself once errors are evaluated?

Thanks.

**Comment by klen** [comment]
Set "pymode_lint_cwindow = 0" and use ":lopen" when you want to see errors.
