### ISSUE TITLE
Additional "E121: Undefined variable: from" errors with Vim without python support

### ISSUE THREAD

**Issue by blueyed** [klen/python-mode#490]
There are extraneous errors when Vim is compiled without python support:

    [Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled.
    Error detected while processing …/vim/neobundles/python-mode/autoload/pymode/virtualenv.vim:
    line    3:
    E121: Undefined variable: from
    E15: Invalid expression: from pymode.virtualenv import enable_virtualenv
    Error detected while processing …/vim/neobundles/python-mode/ftplugin/python/pymode.vim:
    line   12:
    E121: Undefined variable: from

Only the first error should appear from/via python-mode.

**Comment by MarkusMeskanen** [comment]
Getting this same error...

**Comment by klen** [comment]
Thank you for the feedback.
