### ISSUE TITLE
Method extraction fails with "Unhandled exception in Pymode: get_changes()" [$5]

### ISSUE THREAD

**Issue by dset0x** [klen/python-mode#494]
Using the `g:pymode_rope_extract_method_bind` keybind on a sample [function](http://rope.sourceforge.net/overview.html#extract-method) fails with the following error:

>  [Pymode]: error: Unhandled exception in Pymode: get_changes() takes exactly 2 arguments (3 given)

**Comment by leconteur** [comment]
I see the same problem here.

**Comment by br0th3r** [comment]
Same here

**Comment by arkravitz** [comment]
Same here? Any chance this will be fixed soon?

**Comment by thisfred** [comment]
I have switched away from python_mode to use syntastic (with prospector to get even more tooling than python-mode offers) and ropevim, which work fine.
