### ISSUE TITLE
Rope cache corruption

### ISSUE THREAD

**Issue by ccope** [klen/python-mode#497]
I started having a problem with autocomplete not working, I couldn't ^C-g to open docs, and if I typed a period in insert mode the cursor would move back over it, making it difficult to code. The only error message I saw was ```[Pymode]: error: could not find MARK```. I eventually tried running :PymodeRopeRegenerate, and when *that* threw the same error I tried rm -r'ing the .ropeproject directory and re-running :PymodeRopeRegenerate, which made everything start working again.

**Comment by mcepl** [comment]
If you can reproduce the issue without `python-mode` (i.e., uninstall it completely, and install [rope](https://github.com/python-rope/rope), [ropemode](https://github.com/python-rope/ropemode), and [ropevim](https://github.com/python-rope/ropevim), please file an issue report at `ropevim` issue tracker. Thank you.

**Comment by ccope** [comment]
Ah, closing this issue then.
