### ISSUE TITLE
Is there a way to abort infinite loops?

### ISSUE THREAD

**Issue by Ps-Pencil** [klen/python-mode#527]
vim just hangs in "code running" screen. Ctrl-C does not work.

(I re-looked at this question, and realise I should have provided more information, because I cannot understand myself then....). I think what I was asking is if I use `<leader>r` to run the python code and there is a infinite loop in the code, there is no way to halt the program.

**Comment by ryneeverett** [comment]
https://github.com/klen/python-mode/issues/288

**Comment by ryneeverett** [comment]
My solution is:

```
let g:pymode_run = 0
```

because without the ability to easily kill the process this feature isn't useful.

**Comment by Ps-Pencil** [comment]
Does that effectively disable the plugin?

**Comment by ryneeverett** [comment]
@Ps-Pencil It disables the `pymode_run` feature, which seems like the best course of action to me since there's no good way to kill the process.

**Comment by Ps-Pencil** [comment]
Ok~ thanks. Wondering if there is a way to send the ^C signal.
