### ISSUE TITLE
Calling organize_imports() on bufferwrite disables syntax highlighting

### ISSUE THREAD

**Issue by nicorevin** [klen/python-mode#530]
Tried two cases:
* `autocmd BufWritePost *.py call pymode#rope#organize_imports()` in vimrc
* adding to `fun! pymode#buffer_post_write()`

OS: arch/yosemite
vim: 7.4.617-1/7.4.488
vimrc: [vimrc](https://github.com/nicorevin/dotfiles/blob/e3cf586b237bda8022adfec05494c741881b3dd9/.vimrc)

**Comment by dset0x** [comment]
Keep in mind that `organize_imports` will drop imports which are unused. If for example you have this file:

```python
import re

a = 'hello'
b = re.match('h', a)
```
and you comment out the last line and call `organize_imports`, `import re` will be removed from the file.

**Comment by bsandrow** [comment]
An even worse case, would be to call it on a file that imports things for export. For example, importing functions from submodules into the package `__init__.py`.

**Comment by nicorevin** [comment]
OK, thus I treat highlight reset as "hey, watch out, kid!"
