### ISSUE TITLE
loclist is not populated when g:pymode_lint_cwindow = 0

### ISSUE THREAD

**Issue by Ram-Z** [klen/python-mode#535]
When setting the above setting the loclist is not shown as expected but it is also not populated at all, so I can't show it later with `:lopen`

The issue seems to be in [lint.vim#L69](https://github.com/klen/python-mode/blob/develop/autoload/pymode/lint.vim#L69) since the loclist is only populated in [show()](https://github.com/klen/python-mode/blob/develop/autoload/pymode/tools/loclist.vim#L67).

**Comment by klen** [comment]
Fixed now, thank you for the feedback.
