### ISSUE TITLE
feature request play nice with jedi-vim

### ISSUE THREAD

**Issue by jerowe** [klen/python-mode#538]
Is there anyway to disable autocompletion in python-mode so I can use the autocompletion features of jedi-vim with all the other features of python-mode?

**Comment by feoh** [comment]
Hi @jerowe you can disable the built in completion by disabling the rope plugin.  This will also disable the refactoring commands, but they come as a package - perhaps there's a way to disable JUST the completion - not sure, but in any case you can turn the whole thing off with:
```
let g:pymode_rope=0
```
in your .vimrc

Good luck!

**Comment by jerowe** [comment]
Thanks! I tried this and it did work. ;)
