### ISSUE TITLE
Can't override max line length for pep8 checker

### ISSUE THREAD

**Issue by catlee** [klen/python-mode#559]
I can't figure out how to override the default max line length for the pep8 checker, other than modifying lint/pylama_pep8/pep8.py directly.

**Comment by squisher** [comment]
This used to work just fine by adding a **pylama.ini** file to your project:
```ini
[pylama:pep8]
max_line_length=100
```
However, something past the 0.8.1 release broke loading the configuration.

**Comment by squisher** [comment]
git bisect points me to:
> commit 00c6c75bb2624dfc08c1fc57ad91abb9f3b2fdf8
> Author: Kirill Klenov <horneds@gmail.com>
> Date:   Mon Jun 16 19:00:58 2014 +0400
> 
>    Full tunning with code checkers. Also added g:pymode_options_max_line_length

**Comment by klen** [comment]
Thanks @squisher

**Comment by mojia** [comment]
If you can not find pylama.ini, you can edit pycodestyle.py file MAX_LINE_LENGTH field to 240 for example.

path:
~/.atom/packages/linter-pylama/bin/deps/pycodestyle.py

**Comment by diraol** [comment]
@mojia this issue has been closed a long time ago. Let's try not to bring it up without need. ;)

Anyway, I wouldn't ever edit `.py` files for this specific reason (change pep8 configs).

I would rather go with `setup.cfg` or `pycodestyle.ini` or `pylint.ini`.

They can be added to your project root directory (same place as `setup.py`) or to your user home directory.
