### ISSUE TITLE
How do I press Ctrl+c+rd

### ISSUE THREAD

**Issue by canyon289** [klen/python-mode#585]
I'm watching the video for this plugin and at one point it mentions I can press Ctrl+c+rd. I'm very new to vim and I don't understand exactly what I'm supposed to do, I can't press all the buttons at the same time so what's the intention here?

Thanks in advance

![image](https://cloud.githubusercontent.com/assets/7213793/9242635/8d6dbf66-4139-11e5-9581-188c458f67be.png)

**Comment by HuStmpHrrr** [comment]
it means a sequence of
```
<C-c>
r
d
```
instead of pressing all of them together, which probably what you thought it was.

**Comment by canyon289** [comment]
So I tried this but what ends up happening is that the character under the cursor gets replaced from the r d command, and the documentation show. I tried doing it really fast but there was no difference. 

I know this has to be something simple that I'm just missing. Thank you for the help

**Comment by HuStmpHrrr** [comment]
in Vim, type
```
:map
```
and have a eyeball search to see if the binding you mentioned is there or not first.

**Comment by canyon289** [comment]
Thanks for mentioning the map command, i didn't know that exited. Turns out in the version of Pymode that I have its <C-C>d which works exactly as intended. Much appreciated

![image](https://cloud.githubusercontent.com/assets/7213793/9290071/7e6f96c2-4339-11e5-941e-8e2ad2efb411.png)
