### ISSUE TITLE
PymodeLint reports there are errors in my code while there isn't

### ISSUE THREAD

**Issue by HuStmpHrrr** [klen/python-mode#588]
following is my code:

```python
def zipdict(*dicts):
    return {k: tuple(map(lambda d: d[k], dicts))
              for k in reduce(lambda s1, s2: s1 & s2, map(set, dicts))}
```
and it reports:
>test2.py|9 col 1 error| E0602 undefined name 'k' [pyflakes]

that's not true however. in console, i ran:
```
>>> zipdict({1:1, 2:2}, {1:3, 2:4})
{1: (1, 3), 2: (2, 4)}
```
that works perfectly.

why would that complains about `k`? I tried with other comprehension like:
```python
def abc():
    return {k:100
              for k in range(20)}
```
and it doesn't complain(which is correct).

**Comment by klen** [comment]
Actually I think it's `pylint`, `pyflakes` related issue.
