### ISSUE TITLE
error when processing lint.vim

### ISSUE THREAD

**Issue by rlowrance** [klen/python-mode#600]
When I start vim with a fresh download of python-mode, I get an error message from vim while vim is processing the lint.vim file
    
    Error detected while processing <snip>/.vim/bundle/python-mode/autoload/pymode/lint.vim
    line  1:

I'm running RedHat Linux.

Have I not installed python-mode correctly?

**Comment by klen** [comment]
Can you type `:messages` and provide the given traceback here?

**Comment by Ingimar** [comment]
I had this issue (well that was also my first message, so it might not be the same root cause) and turned out to be my old install of python throwing the error (2.7 roughly 2010). Updating to 2.7.10 (May 23, 2015 win32).

**Comment by rlowrance** [comment]
Here is what :messages printed after I executed vim parcels.py

The parcels.py file is attached.

Messages maintainer: Bram Moolenaar <Bram@vim.org>
"parcels.py" 129L, 3875C
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
  File "/home/lowrance/.vim/bundle/python-mode/pymode/lint.py", line 10, in
<mod
ule>
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
    from pylama.lint.pylama_pylint import Linter
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
  File
"/home/lowrance/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_py
lint/__init__.py", line 12, in <module>
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
    from .main import Linter  # noqa
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
  File
"/home/lowrance/.vim/bundle/python-mode/pymode/libs/pylama/lint/pylama_py
lint/main.py", line 10, in <module>
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
    from pylint.lint import Run
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
  File "/home/lowrance/.vim/bundle/python-mode/pymode/libs/pylint/lint.py",
line
 642
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
    control_pragmas = {'disable', 'enable'}
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
                                ^
Error detected while processing
/home/lowrance/.vim/bundle/python-mode/autoload/
pymode/lint.vim:
line    1:
SyntaxError: invalid syntax
Press ENTER or type command to continue



Roy Lowrance
cds.nyu.edu
tel: 347 255 2544

**Comment by klen** [comment]
I think you have VIM compiled with python 2.6. Last pylint doesnt support the python version. I've fixed the issue in develop branch, but in that case pylint will not work.

**Comment by rlowrance** [comment]
Thank you. I will investigate. - Roy


Roy Lowrance
cds.nyu.edu
tel: 347 255 2544

**Comment by apeforest** [comment]
I still got the same issue using the develop branch. My python version is 2.7.13
Thanks!

Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 30, in
<module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/Users/lyuan/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 21, in
<module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import io
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py
", line 51, in <module>
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    import _io
Error detected while processing /Users/lyuan/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/pyt
hon2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder

**Comment by monological** [comment]
This happens because there are still old python2 .pyc files. To fix this go to the python-mode directory and run `find . -name '*.pyc' -delete`. This made the error go away for me.

**Comment by cutelittleturtle** [comment]
I have the same problem. I am using: Ubuntu 17.10, Vim 8.0, python2 and python3 installed on `/usr/bin`

I have tried `delete *.pyc` -> didn't work
I have tried remove custom python path in `bashrc` -> didn't work
I have tried reinstall `vim` and `python3` and then update `spf13` -> didn't work

The ultimate solution is to **recompile** vim with python and python3, following [this guide](https://gist.github.com/odiumediae/3b22d09b62e9acb7788baf6fdbb77cf8). It then works.

The interesting thing is I have similar setup on Ubuntu and Arch linux. The Arch linux didn't pose this problem at all.

**Comment by diraol** [comment]
If I'm not mistaken, the default vim does not have python support.
You must install, with apt, pytho-nox to have such support (or compile it
by yourself) - I think that the support is for python3 only in this case.

Em 3 de dez de 2017 20:02, "cutelittleturtle" <notifications@github.com>
escreveu:

**Comment by pazz** [comment]
I get the same problem with vim 8.1 from vim-nox from debian testing. It has python 3 support compiled in (`vim --version` lists `+python3`). I'm on Python 3.6.7
