### ISSUE TITLE
pymode_lint_write is set to 0 still working on every save

### ISSUE THREAD

**Issue by arunraman** [klen/python-mode#605]
I have disabled the lint on every save in my .vimrc but it still shows errors and warning on every save.

this is my .vimrc

https://github.com/arunraman/MyVim/blob/master/.vimrc

**Comment by boltnev** [comment]
@arunraman seems like `pymode_lint_write` was renamed to `pymode_lint_on_write`(if you are still interested in this issue).

**Comment by arunraman** [comment]
Thanks
