### ISSUE TITLE
PyLint version is outdated, is it possible to use a custom one?

### ISSUE THREAD

**Issue by nbdsp** [klen/python-mode#611]
In gvim compiled with python3 and python 3.5 on the machine pylint on analysing any ".py" file returns error:

`tst.py|1 F| F0002 <class 'AttributeError'>: 'Call' object has no attribute 'starargs' [pylint]`

Maybe somehow linked to this issue: https://bitbucket.org/logilab/pylint/issues/643/attributeerror-call-object-has-no

Is it possible to replace the Pylint version used by Pymode without tinkering with Pymode internals?

**Comment by agilezebra** [comment]
You can install from the latest source and things will be much better. I just did this today:
```bash
$ cd /tmp
$ hg clone https://bitbucket.org/logilab/astroid
$ hg clone https://bitbucket.org/logilab/pylint
[edit here - see below]
# pip3 uninstall astroid
# pip3 uninstall pylint
# pip3 install astroid/
# pip3 install pylint/
```
This will get you to this version right now, which works really well with python3.5, albeit with these 3 warnings showing:
``` bash
$ pylint --version
Warning: option profile is obsolete and it is slated for removal in Pylint 1.6.
Warning: option required-attributes is obsolete and it is slated for removal in Pylint 1.6.
Warning: option ignore-iface-methods is obsolete and it is slated for removal in Pylint 1.6.
pylint 1.5.0, 
astroid 1.4.0
Python 3.5.0 (default, Sep 23 2015, 04:41:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
```
You can easily remove those 3 warnings by greping for the 3 option strings and commenting out the option in the module. The 3 files with options are (from the pylint dir):
- lint.py (profile)
- checkers/base.py (required-attributes)
- checkers/classes.py (ignore-face-methods). 
Once you've comment those 3 entries out, you back to a fully working lint. You can of course do this in the cloned source code directories before you run the install, which may be a bit easier. It's also helpful if you want to install in multiple places as you can just tar up the 2 dirs and distribute.

**Comment by nbdsp** [comment]
Thanks, will try it.
