### ISSUE TITLE
au pymode  clears when quit one of splitted windows

### ISSUE THREAD

**Issue by mpyatishev** [klen/python-mode#620]
I encountered such a problem: when I open the file, then make a split window and then quit (```^Wq```) one of the windows, the ```au pymode``` cleared completely so automatic ```PymodeLint``` does not work any more.

**Comment by peikk0** [comment]
Same here.

**Comment by FBruynbroeck** [comment]
I have the same problem.

**Comment by FBruynbroeck** [comment]
Applying the following patch seems to fix it: https://github.com/klen/python-mode/issues/511#issuecomment-84455224

**Comment by mpyatishev** [comment]
Thanks @FBruynbroeck ! I create pull request to resolve this issue.
