### ISSUE TITLE
why g:pymode_lint_cwindow = 1 still not open quickfix windows?

### ISSUE THREAD

**Issue by crazy-canux** [klen/python-mode#644]
autocmd FileType python map <buffer> <leader>8 :PymodeLint<CR>

I use \ + 8 to start the checkers.
Just show "[pymode] found errors and warnings: 1".
Not open quickfix  windows.

**Comment by koterpillar** [comment]
This is possible when you have Syntastic installed, in which case `au FileType python let b:syntastic_auto_loc_list = 0` will fix it.

**Comment by mbrunnen** [comment]
+1

**Comment by crazy-canux** [comment]
Sure, thanks.
