### ISSUE TITLE
Ideas about how to integrate pylint-django?

### ISSUE THREAD

**Issue by philbert** [klen/python-mode#647]
I'm doing some django development and I'm running onto django-specific errors like this:

```[no-member] Class 'Question' has no 'objects' member```

There is a pylint plugin called [pylint-django](https://github.com/landscapeio/pylint-django) that apparently resolves these errors, but I've not managed to successfully integrate it with python-mode. Any suggestions?

**Comment by philbert** [comment]
Seems I managed to resolve this by installing pylint-django into my virtualenv and setting up a .pylintrc file with the following contents:

```
[MASTER]
load-plugins=pylint_django
```

Now when pylint in vim the errors disappear as expected.

**Comment by KianMehrabi** [comment]
what do you mean by setting up , should i just make a file name .pylintrc in the env direcroty 
sorry for questions i am new

**Comment by philbert** [comment]
I no longer have this set up, but I guess the .pylintrc file must either be in the root of your app, or in your user's home folder.
