### ISSUE TITLE
Switch license to MIT/BSD or add LGPL message to top

### ISSUE THREAD

**Issue by tony** [klen/python-mode#648]
I just found out this was LGPL after assuming otherwise for quite a while.

Files like https://github.com/klen/python-mode/blob/develop/pymode/autopep8.py could lead one to unwittingly copy code that's under the LGPL thinking it's MIT.

* (L)GPL recommends keeping a a partial notice  at the top of files to prevent accidental copying. http://producingoss.com/en/license-quickstart.html#license-quickstart-applying

  LGPL isn't really a good fit for scripting languages. We're not concerned about binary blobs. The legal language of the GPL is catered to compiled languages - making its' application of what triggers a derivative in python contentious.

* The simpler solution is to pick the simpler license. MIT/BSD/ISC is nice.

  In the python community pretty much all of our projects are permissively licensed and are very active.

**Comment by vlad003** [comment]
It's pretty obvious this is LGPL; there's a COPYING file and it also says it in the README.

Plus, you'd need to get approval from all 76 contributors to relicense all their contributions under a new license.

In terms of `autopep8.py`, IANAL, but as far as I can tell, you can consider that file licensed under MIT but the combined work is licensed under LGPLv3.

**Comment by tony** [comment]
> It's pretty obvious this is LGPL; there's a COPYING file and it also says it in the README.
> In terms of autopep8.py, IANAL, but as far as I can tell, you can consider that file licensed under MIT but the combined work is licensed under LGPLv3.

I appreciate you're familiarity, but there are more contingencies to consider than what is obvious to you. That's why there's a prelude on GPL projects, take for instance this [makefile.src.inc](https://git.openttd.org/?p=branches/1.5.git;a=blob;f=Makefile.src.in;h=1d654d283f328ec7ae15e29160dcd4a7f1da6c26;hb=18bbb8218046cc9350dea78f9c2aa12ab2337a77) for OpenTDD.

A person unfamiliar with open source and project structures can't be relied on to seek out a README or COPYING. The purpose of the prelude is to direct them to the file, and to make note it is part of a (L)GPL project.

> Plus, you'd need to get approval from all 76 contributors to relicense all their contributions under a new license.

http://licenses.beberlei.de/

Most of the code is Klen's. If you look at https://github.com/twbs/bootstrap/issues/2054 its pretty hilarious to see how people with the tiniest changes are the holdouts for GPL.

<img width="784" alt="screen shot 2016-01-16 at 4 26 58 am" src="https://cloud.githubusercontent.com/assets/26336/12371901/770d0cb8-bc09-11e5-8eb8-fb31c2a9e598.png">

More and more often, its sad to see GPL being used to take the low road by a small few, often which know little of what they're talking about. Some touting (L)GPL probably never read it. On mailing lists, becoming norm for them to conveniently interject out of nowhere just to suck up time and space. These days, I'd guess half of the people touting GPL use it more or less as a sports jersey than being invested in what its really for.

I don't want to waste too much educating others on licenses, honestly I'd rather make my own project than shepherd another license change. if @klen feels open to changing, he can reopen.
